version: "3"
services:
  tiger-db:
    image: mysql:8.0.30
    container_name: tiger-db
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_0900_ai_ci",
      "--sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES",
      "--max_connections=1024",
      "--lower_case_table_names=1",
      "--default-time-zone=+8:00",
      "--innodb-buffer-pool-size=128M"
    ]
    restart: always
    volumes:
      - ./dataDir:/var/lib/mysql
      - ./init-tiger.sql:/docker-entrypoint-initdb.d/init-tiger.sql
    environment:
      MYSQL_ROOT_PASSWORD: e35fr34#232%6y61weq!@d
      TZ: Asia/Shanghai
#    healthcheck:
#      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -uroot -pe35fr34#232%6y61weq!@d" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 1s
      retries: 10
    ports:
      - "13306:3306"
    networks:
      - tiger
  tiger-java:
    image: eclipse-temurin:17.0.8_7-jdk
    restart: always
    ports:
      - "1083:1083"
    volumes:
      - ./workdir:/var/roubao/workdir
      - ./mnt:/mnt
    container_name: tiger-java
    working_dir: /mnt
    command:
      - java
      - -server
      - -Xms512M
      - -Xmx512M
      - -XX:MaxGCPauseMillis=200
      - -XX:MetaspaceSize=256M
      - -XX:MaxMetaspaceSize=512M
      - -jar
      - app.jar
    environment:
      TZ: Asia/Shanghai
      MYSQL_HOST: tiger-db
      MYSQL_PORT: 3306
      MYSQL_DATABASE_NAME: tiger
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: e35fr34#232%6y61weq!@d
      #      项目的工作目录  可通过上面的volumes进行挂载
      BASE_DIR: /var/tiger/workdir
      #      是否自动初始化sql各个版本，默认false，如果true，会自动升根据版本升级sql
      IF_AUTO_INIT_SQL: false
      #      jwt过期时间 以天为单位
      JWT_EXPIRATION: 7
      #      jwt签名
      JWT_SECRET: 123112DFERdsafds323213d
      #      jwt过期时间 以天为单位  此jwt设置是请求文件使用，文件的jwt是单独控制的
      JWT_file_EXPIRATION: 7
      #      jwt签名 此jwt设置是请求文件使用，文件的jwt是单独控制的
      JWT_file_SECRET: 123112DFERdsafds323213dddd
    #    依赖db
    depends_on:
      tiger-db:
        condition: service_healthy
    networks:
      - tiger

  tiger-web:
    image: nginx:latest
    container_name: tiger-web
    restart: always
    privileged: true
    environment:
      TZ: Asia/Shanghai
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./mnt:/mnt
    depends_on:
      - tiger-java
      - tiger-db

    networks:
      - tiger

networks:
  tiger:
    driver: bridge
